# List environments and check if the current environment is active
env-list:
    poetry env list
    @if poetry env list | grep -q "\*"; then \
        echo "The current environment is active."; \
    else \
        echo "The current environment is NOT active."; \
    fi
    just --list

# Install dependencies
install:
    poetry install --no-root


# List outdated packages
outdated:
    poetry show --outdated
    @echo "Run 'just update' to update dependencies."


# Update dependencies
update:
    poetry update

# Display information about the virtual environment
info:
    poetry env info

# Remove virtual environment
cleanup:
    @echo "Removing virtual environment for the current project..."
    poetry env remove $(poetry run which python | sed -E "s|.*/python([0-9].[0-9])$|\1|")
    @echo "Virtual environment removed."

# Run the app with (zero * or more) args
run *args:
    poetry run python main.py {{args}}
